[package]
name = "ccdi-tool-timestamps"
version = "0.1.0"
authors = ["vchvatal"]
edition = "2021"

[dependencies]
fitsio = "0.21.2"
itertools = "0.11.0"
chrono = "0.4.26"

ccdi-common = { path = "../ccdi-common" }

