[package]
name = "ccdi-web-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
yew = { version = "0.21", features = ["csr"] }
yew-websocket = "1.21.0"
gloo = "0.9.0"
gloo-timers = "0.2.6"
base64 = "0.21.0"
web-sys = "*"
wasm-bindgen = "*"

ccdi-common = { path = "../ccdi-common" }
ccdi-image = { path = "../ccdi-image" }
ccdi-imager-interface = { path = "../ccdi-imager-interface" }